### ISSUE TITLE
Error: cb is not a function

### ISSUE THREAD

**Issue by Blagus** [gagle/node-tftp#16]
When working on TFTP provisioning with an IP phone, combined with HTTP proxy from examples, I started getting following error: "Error: cb is not a function".
It was being sent from "error" event ( req.on("error"...); ).
The error was exclusive to the phone, transfer to another PC/server worked fine.

I solved the error by changing lib/protocol/writer.js line 251 from
`this._cb = null;`
to
`this._cb = function() { return false; };`

This seems to work fine in my case, but is there a better solution?
How do I find out what's actually causing this error to show up only when sending files to the phone?

**Comment by oxygen** [comment]
Same error using VMware Player 12 (tested on only Windows):
```
[TFTP] Request from 192.168.137.18 for file path: "pxelinux.0"
Proxying /pxelinux.0
Error: TFTP Aborted
    at fn.IncomingRequest._onMessage (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/server/incoming-request.js:145:17)
    at Socket.<anonymous> (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/server/incoming-request.js:32:6)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:658:8)
[TFTP] Request from 192.168.137.18 for file path: "pxelinux.0"
Proxying /pxelinux.0
{ Error: cb is not a function
    at fn.Request._closeWithError (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/request.js:101:14)
    at fn.Request._sendErrorAndClose (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/request.js:97:7)
    at fn.IncomingRequest._onMessage (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/server/incoming-request.js:136:11)
    at Socket.<anonymous> (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/server/incoming-request.js:32:6)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:658:8) code: 'TypeError' }

```
