### ISSUE TITLE
Error: TFTP Aborted, VMware Player 12 PXE boot, e1000e network card

### ISSUE THREAD

**Issue by oxygen** [gagle/node-tftp#19]
VMware Player 12 on Windows 10 64bit, PXE boot, Intel e1000e network card, and the TFTP server runs on another VM Linux box, not on Windows:

```
[TFTP] Request from 192.168.137.18 for file path: "pxelinux.0"
Proxying /pxelinux.0
Error: TFTP Aborted
    at fn.IncomingRequest._onMessage (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/server/incoming-request.js:145:17)
    at Socket.<anonymous> (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/server/incoming-request.js:32:6)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:658:8)
[TFTP] Request from 192.168.137.18 for file path: "pxelinux.0"
Proxying /pxelinux.0
Error: Timed out
    at Timeout.<anonymous> (/mnt/autofs/ExportVHosts/TFTP2HTTP/node_modules/tftp/lib/protocol/request.js:143:24)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

I have applied a fix to get the 2nd error about the timeout (I think VMware sends a timeout packet?), otherwise I was getting `cb is not a function`, from here: https://github.com/gagle/node-tftp/issues/16

The 1st error I have no idea how to solve and is the one this bugs refers to.

The `TFTP Aborted` message appears immediately.

VMware output:
```
CLIENT MAC ADDR: 00 00 00 00 03 03 GUID {server UUID here}
CLIENT IP: some IP, MASK: some mask, DHCP IP: dhcp server IP
GATEWAY IP some router IP
PXE-E35: TFTP read timeout
PXE-E39: TFTP cannot read from connection
PXE-M0F: Exiting Intel PXE ROM
```

 tcpdump -i ens160 -n udp port 69 -v
```
[root@vm ~]# tcpdump -i ens160 -n udp port 69 -v
tcpdump: listening on ens160, link-type EN10MB (Ethernet), capture size 262144 bytes
15:10:54.287103 IP (tos 0x0, ttl 20, id 3, offset 0, flags [none], proto UDP (17), length 55)
    192.168.137.19.ah-esp-encap > 192.168.137.2.tftp:  27 RRQ "pxelinux.0" octet tsize 0
15:10:54.375956 IP (tos 0x0, ttl 20, id 5, offset 0, flags [none], proto UDP (17), length 60)
    192.168.137.19.acp-port > 192.168.137.2.tftp:  32 RRQ "pxelinux.0" octet blksize 1456
```

**Comment by oxygen** [comment]
Sorry, my bad, I was setting a NaN size on PutStream.setSize().

Proposed change to validate the value:
https://github.com/gagle/node-tftp/pull/20
